# Generated by Django 5.0.6 on 2024-06-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='instructor_name',
        ),
    ]
