# Generated by Django 5.0.6 on 2024-06-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_instructor_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='main.instructor'),
        ),
    ]
