# Generated by Django 5.0.6 on 2024-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_classroom_classroom_unique_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
