# Generated by Django 5.0.6 on 2024-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_total_student_intake_total_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
