# Generated by Django 5.0.6 on 2024-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_intake_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
