# Generated by Django 5.0.6 on 2024-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_instructor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
