# Generated by Django 5.0.6 on 2024-07-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_classroom_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
