# Generated by Django 5.0.6 on 2024-07-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
