# Generated by Django 5.0.6 on 2024-07-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
