# Generated by Django 5.0.6 on 2024-07-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
