# Generated by Django 5.0.6 on 2024-07-22 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_timetable_timetableentry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetable',
            table='timetable',
        ),
        migrations.AlterModelTable(
            name='timetableentry',
            table='timetable_entry',
        ),
    ]
