# Generated by Django 5.0.6 on 2024-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_intake_unique_intake_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='intake',
            name='unique_intake_code',
        ),
        migrations.AddConstraint(
            model_name='intake',
            constraint=models.UniqueConstraint(fields=('intake_code',), name='unique_intake_code'),
        ),
    ]
