# Generated by Django 5.0.6 on 2024-07-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
