# Generated by Django 5.0.6 on 2024-07-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='intake_id',
            new_name='intake',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='student_profile',
        ),
    ]
