# Generated by Django 5.0.6 on 2024-07-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_intake_id_studentprofile_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default=222, max_length=100),
            preserve_default=False,
        ),
    ]
