# Generated by Django 5.0.6 on 2024-07-26 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_studentprofile_intake_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='intake',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.intake'),
        ),
    ]
