# Generated by Django 5.0.6 on 2024-07-26 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_studentprofile_created_at_studentprofile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='classroom_id',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='intake_id',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='section_id',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.instructor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='intake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.intake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.section'),
            preserve_default=False,
        ),
    ]
