# Generated by Django 5.0.6 on 2024-07-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_timetableentry_classroom_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
                ('max_time_gap', models.PositiveIntegerField()),
                ('min_time_gap', models.PositiveIntegerField()),
                ('lunch_start', models.PositiveIntegerField()),
                ('lunch_duration', models.PositiveIntegerField()),
                ('delayed_lunch_start', models.PositiveIntegerField()),
                ('min_classes_per_day', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
