# Generated by Django 5.0.6 on 2024-07-26 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='delayed_lunch_start',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='lunch_duration',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='lunch_start',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='max_time_gap',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='min_classes_per_day',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='min_time_gap',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='start_time',
        ),
        migrations.AddField(
            model_name='feedback',
            name='delayed_lunch_start_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='end_time_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='lunch_duration_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='lunch_start_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='max_time_gap_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='min_classes_per_day_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='min_time_gap_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='start_time_rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
