# Generated by Django 5.0.6 on 2024-07-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_intake_total_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
